databases:
  - name: iot-energy-cloud-db
    databaseName: iess_db
    user: iess
    plan: free

services:
  - type: web
    name: iot-energy-cloud
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DEMO_MODE
        value: "false"
      - key: MQTT_HOST
        value: broker.hivemq.com
      - key: MQTT_PORT
        value: "1883"
      - key: POSTGRES_URL
        fromDatabase:
          name: iot-energy-cloud-db
          property: connectionString
      - key: INFLUX_URL
        sync: false
      - key: INFLUX_TOKEN
        sync: false
      - key: INFLUX_ORG
        sync: false
      - key: INFLUX_BUCKET
        value: realtime
      - key: REDIS_URL
        sync: false

  - type: worker
    name: iot-energy-cloud-simulator
    env: python
    plan: free
    rootDir: simulator
    buildCommand: pip install paho-mqtt>=2.0.0
    startCommand: python main.py
    envVars:
      - key: MQTT_HOST
        value: broker.hivemq.com
      - key: MQTT_PORT
        value: "1883"
